# Generated by Django 5.0.2 on 2024-02-18 12:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Condidate name')),
                ('fname', models.CharField(max_length=200, verbose_name='Father name')),
                ('pname', models.CharField(max_length=200, verbose_name='Patient name')),
                ('serviceType', models.CharField(max_length=200, verbose_name='Service Type')),
                ('Entrytime', models.TimeField(default=None, verbose_name='Entry Time')),
                ('Exittime', models.TimeField(default=None, verbose_name='Exit Time')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Condidate')),
            ],
        ),
    ]
