# Generated by Django 5.0.2 on 2024-02-18 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condidate',
            name='Entrytime',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Entry Time'),
        ),
        migrations.AlterField(
            model_name='condidate',
            name='Exittime',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Exit Time'),
        ),
    ]
