# Generated by Django 5.0.2 on 2024-02-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_condidate_entrytime_alter_condidate_exittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condidate',
            name='Exittime',
            field=models.TimeField(default=None, verbose_name='Exit Time'),
        ),
    ]
